/**
 * legacyMissedSubmissionArchive.js
 *
 * Phase 65.1 rollout cleanup.
 *
 * The previous compliance implementation may already have created
 * `missed_submission` / `absent_submission` penalty rows for
 * historical days (i.e. days that pre-date the new
 * "Missed Submission Effective From" cutoff).  Those rows are still
 * showing up on employee dashboards, in Fines & Penalties, and as
 * pending reopen requests.
 *
 * This module runs ONCE at server boot and flips those rows'
 * `archivedPreRollout` flag to true.  Every user-facing read path
 * already filters that flag out, so the effect is instant:
 *
 *   - Employees stop seeing those old warnings.
 *   - HR's Fines & Penalties stops listing them.
 *   - Submission Review stops offering Send Back for them.
 *
 * We do NOT delete anything.  The rows remain in the database for
 * audit; the `archivedPreRollout` flag is enough to hide them.
 * Notifications generated by the earlier implementation are handled
 * separately (see the notification-side hide, below).
 */
const Penalty = require('../models/Penalty');
const Notification = require('../models/Notification');
const { MISSED_SUBMISSION_EFFECTIVE_FROM } = require('../config/complianceRollout');

const runOnce = async () => {
  try {
    const r = await Penalty.updateMany(
      {
        category: { $in: ['missed_submission', 'absent_submission'] },
        targetDate: { $lt: MISSED_SUBMISSION_EFFECTIVE_FROM },
        archivedPreRollout: { $ne: true },
      },
      { $set: { archivedPreRollout: true } },
    );
    if (r?.modifiedCount > 0) {
      console.log(`[legacy-compliance-archive] archived ${r.modifiedCount} pre-rollout penalty row(s)`);
    }
  } catch (e) {
    console.error('[legacy-compliance-archive] penalties failed:', e.message);
  }

  // Notifications produced by the previous implementation carried
  // titles like "Performance penalty applied" or "Missed Submission".
  // We hide them from the employee's dashboard panel by stamping
  // `dismissedFromDashboardAt` (the existing Phase-46 hide flag).
  // The rows STAY in the inbox as historical proof of delivery --
  // spec: "Do NOT delete historical notifications."  Best-effort;
  // never blocks boot.
  try {
    const now = new Date();
    const r2 = await Notification.updateMany(
      {
        createdAt: { $lt: MISSED_SUBMISSION_EFFECTIVE_FROM },
        type: 'general',
        title: { $in: [
          'Performance penalty applied',
          'Warning: possible penalty',
          'Missed Submission',
        ] },
        dismissedFromDashboardAt: { $exists: false },
      },
      { $set: { dismissedFromDashboardAt: now } },
    );
    if (r2?.modifiedCount > 0) {
      console.log(`[legacy-compliance-archive] hid ${r2.modifiedCount} pre-rollout notification(s) from dashboard`);
    }
  } catch (e) {
    console.error('[legacy-compliance-archive] notifications failed:', e.message);
  }
};

const start = () => { setImmediate(() => runOnce().catch(() => {})); };

module.exports = { runOnce, start };
