import { useEffect, useState } from 'react';
import api from '../../api/axios';
import { Loader, EmptyState } from '../../components/Loader.jsx';
import { fmtMoney, authUrl } from '../../utils/helpers';

export default function MySalary() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/salary/mine').then(({ data }) => { setItems(data); setLoading(false); });
  }, []);

  if (loading) return <Loader />;

  return (
    <div className="space-y-5">
      <h1 className="text-2xl font-bold">My Salary Slips</h1>

      {items.length === 0 && <EmptyState title="No salary slips yet" subtitle="Slips are generated by HR each month." />}

      <div className="space-y-6">
        {items.map((s) => <Payslip key={s._id} slip={s} />)}
      </div>
    </div>
  );
}

/** Normalise a slip (new or legacy) into a render model. */
function viewModel(s) {
  if (s.payroll && s.payroll.earnings) {
    return {
      e: s.payroll.earnings, d: s.payroll.deductions,
      employer: s.payroll.employer || { pf: 0, esic: 0, total: 0 },
      ctc: s.payroll.ctc || null,
      net: s.payroll.netPayable, att: s.payroll.attendanceSummary || {},
    };
  }
  const gross = s.grossSalary || 0;
  return {
    e: { basic: gross, hra: 0, conveyance: 0, medical: 0, special: 0, other: 0, bonus: 0, incentives: s.bonuses || 0, bonuses: s.bonuses || 0, grossEarnings: gross + (s.bonuses || 0) },
    d: { pf: 0, esic: 0, pt: 0, tds: 0, halfDay: 0, unpaidLeave: 0, attendance: 0, penalties: s.deductions || 0, totalDeductions: s.deductions || 0 },
    employer: { pf: 0, esic: 0, total: 0 }, ctc: null,
    net: s.netSalary ?? gross,
    att: {
      totalDays: (s.workingDays || 0) + (s.weeklyOffDays || 0),
      presentDays: s.presentDays || 0, paidLeaves: s.paidLeaves || 0, unpaidLeaves: s.unpaidLeaves || 0,
      halfDayCount: (s.halfPaidDays || 0) + (s.halfUnpaidDays || 0), weeklyOffDays: s.weeklyOffDays || 0,
      lopDays: s.unpaidLeaves || 0, attendancePercentage: s.workingDays ? Math.round(((s.payableDays || 0) / s.workingDays) * 100) : 0,
    },
  };
}

function Payslip({ slip: s }) {
  const { e, d, employer, ctc, net, att } = viewModel(s);
  const monthLabel = (() => {
    try { const [y, m] = s.month.split('-').map(Number); return new Date(Date.UTC(y, m - 1, 1)).toLocaleString('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' }); }
    catch { return s.month; }
  })();

  // Label swap (UI-only):
  //   Bonus                  <- e.special       (DB field: salaryStructure.specialAllowance)
  //   Special Allowance      <- e.bonus         (DB field: salaryStructure.bonus)
  //   Additional Compensation <- e.incentives    (DB field: salarySlip.bonuses / bonusItems)
  // DB names, calculations, and totals are unchanged.
  const earningRows = [
    ['Basic Salary', e.basic], ['HRA', e.hra], ['Conveyance', e.conveyance],
    ['Medical Allowance', e.medical], ['Bonus', e.special],
    ['Other Allowances', e.other], ['Special Allowance', e.bonus],
    ['Additional Compensation', e.incentives ?? e.bonuses],
  ].filter((r) => r[1]);
  if (earningRows.length === 0) earningRows.push(['Basic Salary', e.basic]);

  const deductionRows = [
    ['PF (EPF)', d.pf], ['ESIC', d.esic], ['Professional Tax', d.pt], ['Income Tax (TDS)', d.tds],
    ['Half-Day Deduction', d.halfDay], ['Unpaid Leave Deduction', d.unpaidLeave],
    ['Absent Deduction', d.attendance], ['Penalties / Other', d.penalties],
  ].filter((r) => r[1]);

  return (
    <div className="bg-white rounded-xl shadow-sm overflow-hidden border-t-4" style={{ borderTopColor: '#1a365d' }}>
      {/* Header */}
      <div className="flex items-start justify-between px-6 py-5 border-b border-slate-200">
        <div>
          <div className="text-lg font-bold" style={{ color: '#1a365d' }}>Payslip</div>
          <div className="text-xs text-slate-500 mt-0.5">{monthLabel}</div>
          {s.payslipNumber && <div className="text-[11px] text-slate-400">{s.payslipNumber}</div>}
        </div>
        <a className="btn-secondary" href={authUrl(`/api/salary/${s._id}/pdf`)} target="_blank" rel="noreferrer">Download PDF</a>
      </div>

      {/* Attendance */}
      <div className="px-6 pt-4">
        <SectionTitle>Attendance</SectionTitle>
        <div className="grid grid-cols-3 sm:grid-cols-6 gap-2 mb-4">
          <Mini label="Total" value={att.totalDays ?? '-'} />
          <Mini label="Present" value={att.presentDays ?? 0} />
          <Mini label="Paid Lv" value={att.paidLeaves ?? 0} />
          <Mini label="Half Days" value={att.halfDayCount ?? 0} />
          <Mini label="LOP" value={att.lopDays ?? 0} />
          <Mini label="Attendance" value={`${att.attendancePercentage ?? 0}%`} />
        </div>
      </div>

      {/* Earnings / Deductions */}
      <div className="px-6 grid md:grid-cols-2 gap-5">
        <div>
          <SectionTitle>Earnings</SectionTitle>
          <FinTable rows={earningRows} totalLabel="Gross Total" total={e.grossEarnings} totalCls="text-green-700" />
        </div>
        <div>
          <SectionTitle>Deductions</SectionTitle>
          {deductionRows.length
            ? <FinTable rows={deductionRows} totalLabel="Total Deductions" total={d.totalDeductions} totalCls="text-red-700" />
            : <FinTable rows={[['No deductions', 0]]} totalLabel="Total Deductions" total={0} totalCls="text-red-700" />}
        </div>
      </div>

      {/* Employer contributions + CTC */}
      {(employer?.total > 0 || ctc) && (
        <div className="px-6 pt-2">
          <SectionTitle>Employer Contributions &amp; CTC</SectionTitle>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-2 mb-1">
            <Mini label="Employer PF" value={fmtMoney(employer?.pf || 0)} />
            <Mini label="Employer ESIC" value={fmtMoney(employer?.esic || 0)} />
            <Mini label="Employer Total" value={fmtMoney(employer?.total || 0)} />
            <Mini label="Monthly CTC" value={fmtMoney(ctc?.monthly || 0)} />
            <Mini label="Annual CTC" value={fmtMoney(ctc?.annual || 0)} />
          </div>
          <div className="text-[11px] text-slate-400 mb-1">Employer contributions are part of CTC and do not reduce your net pay.</div>
        </div>
      )}

      {/* Net box */}
      <div className="px-6 py-5">
        <div className="rounded-lg px-6 py-4 flex items-center justify-between text-white"
          style={{ background: 'linear-gradient(135deg, #1a365d 0%, #2a4365 100%)' }}>
          <div>
            <div className="text-sm font-medium opacity-90">Net Salary Payable</div>
            <div className="text-[11px] opacity-70">Total CTC − Total Employee Deductions</div>
          </div>
          <div className="text-2xl font-bold">{fmtMoney(net)}</div>
        </div>
      </div>
    </div>
  );
}

const SectionTitle = ({ children }) => (
  <div className="text-xs font-bold uppercase tracking-wide mb-2 pl-2 border-l-4" style={{ color: '#1a365d', borderColor: '#3182ce' }}>
    {children}
  </div>
);

const Mini = ({ label, value }) => (
  <div className="bg-slate-50 rounded-lg py-2 text-center">
    <div className="text-base font-semibold text-slate-900">{value}</div>
    <div className="text-[10px] text-slate-500 uppercase tracking-wide">{label}</div>
  </div>
);

function FinTable({ rows, totalLabel, total, totalCls }) {
  return (
    <table className="w-full text-sm border-collapse">
      <tbody>
        {rows.map(([label, val], i) => (
          <tr key={i}>
            <td className="py-1.5 px-2 border-b border-slate-100 text-slate-600">{label}</td>
            <td className="py-1.5 px-2 border-b border-slate-100 text-right font-medium text-slate-800">{fmtMoney(val)}</td>
          </tr>
        ))}
        <tr className="bg-slate-50">
          <td className={`py-2 px-2 font-semibold ${totalCls}`}>{totalLabel}</td>
          <td className={`py-2 px-2 text-right font-bold ${totalCls}`}>{fmtMoney(total)}</td>
        </tr>
      </tbody>
    </table>
  );
}
